In [ ]:
#C:\Users\Mousumi Das\Desktop\SECRiskFac\1secRisks10K
    #11a,11b

In [2]:
#merge all the csv files
import pandas as pd
#df1= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\13secRisks10K.csv')

In [42]:
df11a= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\11asecRisks10K.csv')
df11b= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\11bsecRisks10K.csv')
df11= pd.concat([df11a, df11b], axis=0)

In [44]:
df11.shape

(5000, 24)

In [45]:
df1= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\1secRisks10K.csv')
df2= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\2secRisks10K.csv')
df3= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\3secRisks10K.csv')
df4= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\4secRisks10K.csv')
df5= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\5secRisks10K.csv')
df6= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\6secRisks10K.csv')
df7= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\7secRisks10K.csv')
df8= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\8secRisks10K.csv')
df9= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\9secRisks10K.csv')
df10= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\10secRisks10K.csv')
# df11a= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\11asecRisks10K.csv')
# df11b= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\11bsecRisks10K.csv')
df12= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\12secRisks10K.csv')
df13= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\13secRisks10K.csv')
df14= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\14secRisks10K.csv')
df15= pd.read_csv(r'C:\Users\Mousumi Das\Desktop\SECRiskFac\15secRisks10K.csv')

In [46]:
df_all = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15], axis=0)

In [47]:
df_all.shape

(77346, 24)

In [147]:
df_all.shape

(77346, 22)

In [150]:
# Create the full file path
file_path = r'D:\SEC_RiskData\risks.csv' #folder_path + file_name

# Save the DataFrame as a CSV file in the specified folder
df_all.to_csv(file_path, index=False)

In [148]:
df_all.tail(1)

,id,accessionNo,cik,ticker,companyName,companyNameLong,formType,description,filedAt,linkToTxt,...,linkToFilingDetails,entities,documentFormatFiles,dataFiles,seriesAndClassesContractsInformation,periodOfReport,effectivenessDate,10k_risks1A,10k_risks7,10k_risks7A
77345,f18ddcaeef0a2485c4be5570750fc362,0000897069-04-000546,1255474,WLLAW,WHITING PETROLEUM CORP,WHITING PETROLEUM CORP (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2004-03-04T16:55:25-05:00,https://www.sec.gov/Archives/edgar/data/125547...,...,https://www.sec.gov/Archives/edgar/data/125547...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '804374', 'document...",[],NaN,NaN,NaN,NaN,Item 7. Management&#146;s Discussion and Anal...,Item 7A. Quantitative and Qualitative Disclos...

In [50]:
df_all.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'id', 'accessionNo', 'cik', 'ticker',
       'companyName', 'companyNameLong', 'formType', 'description', 'filedAt',
       'linkToTxt', 'linkToHtml', 'linkToXbrl', 'linkToFilingDetails',
       'entities', 'documentFormatFiles', 'dataFiles',
       'seriesAndClassesContractsInformation', 'periodOfReport',
       'effectivenessDate', '10k_risks1A', '10k_risks7', '10k_risks7A'],
      dtype='object')

In [51]:
df_all.set_index('Unnamed: 0.1', inplace=True)

In [56]:
df_all = df_all.reset_index(drop=True)

In [58]:
df_all.drop(['Unnamed: 0'], axis=1, inplace=True)

In [59]:
df_all.tail(2)

,id,accessionNo,cik,ticker,companyName,companyNameLong,formType,description,filedAt,linkToTxt,...,linkToFilingDetails,entities,documentFormatFiles,dataFiles,seriesAndClassesContractsInformation,periodOfReport,effectivenessDate,10k_risks1A,10k_risks7,10k_risks7A
77344,47e80e173f36e2b50dbbb0bd337a0002,0000897069-05-000552,1255474,WLLAW,WHITING PETROLEUM CORP,WHITING PETROLEUM CORP (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2005-02-28T13:24:31-05:00,https://www.sec.gov/Archives/edgar/data/125547...,...,https://www.sec.gov/Archives/edgar/data/125547...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '1080257', 'documen...",[],NaN,NaN,NaN,NaN,Item 7 . Management&#146;s Discussion and Ana...,Item 7A. Quantitative and Qualitative Disclos...
77345,f18ddcaeef0a2485c4be5570750fc362,0000897069-04-000546,1255474,WLLAW,WHITING PETROLEUM CORP,WHITING PETROLEUM CORP (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2004-03-04T16:55:25-05:00,https://www.sec.gov/Archives/edgar/data/125547...,...,https://www.sec.gov/Archives/edgar/data/125547...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '804374', 'document...",[],NaN,NaN,NaN,NaN,Item 7. Management&#146;s Discussion and Anal...,Item 7A. Quantitative and Qualitative Disclos...

In [72]:
# #convert df_all to excel
# excel_file_path =r'D:\SEC_RiskData\allRisk.xlsx'
# df_all.to_excel(excel_file_path, index=True)

In [68]:
df_all.isnull().sum()

id                                          0
accessionNo                                 0
cik                                         0
ticker                                     41
companyName                                 0
companyNameLong                             0
formType                                    0
description                                 0
filedAt                                     0
linkToTxt                                   0
linkToHtml                                  0
linkToXbrl                              77346
linkToFilingDetails                         0
entities                                    0
documentFormatFiles                         0
dataFiles                                   0
seriesAndClassesContractsInformation    16837
periodOfReport                          23792
effectivenessDate                       71196
10k_risks1A                              7417
10k_risks7                               1372
10k_risks7A                              3916
dtype: int64

In [93]:
#null_values of 1A sanity check
null_1A = df_all[df_all['10k_risks1A'].isnull()]

In [94]:
null_7 = df_all[df_all['10k_risks7'].isnull()]

In [95]:
null_7A = df_all[df_all['10k_risks7A'].isnull()]

In [96]:
null_1A.shape

(7417, 22)

In [97]:
null_1A.head()

,id,accessionNo,cik,ticker,companyName,companyNameLong,formType,description,filedAt,linkToTxt,...,linkToFilingDetails,entities,documentFormatFiles,dataFiles,seriesAndClassesContractsInformation,periodOfReport,effectivenessDate,10k_risks1A,10k_risks7,10k_risks7A
15,e3e6b74a1ce27be5927d81770bcdd823,0001047469-07-009340,320193,AAPL,APPLE INC,APPLE INC (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2007-11-15T16:49:37-05:00,https://www.sec.gov/Archives/edgar/data/320193...,...,https://www.sec.gov/Archives/edgar/data/320193...,"[{'fiscalYearEnd': '0930', 'stateOfIncorporati...","[{'sequence': '1', 'size': '961251', 'document...",[],NaN,NaN,NaN,NaN,Item 7. Management's Discussion and Analysis ...,Item 7A. Quantitative and Qualitative Disclos...
17,29b8e5f1110747563796b245f2744e27,0001104659-05-058421,320193,AAPL,APPLE COMPUTER INC,APPLE COMPUTER INC (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2005-11-30T21:22:48-05:00,https://www.sec.gov/Archives/edgar/data/320193...,...,https://www.sec.gov/Archives/edgar/data/320193...,"[{'fiscalYearEnd': '0930', 'stateOfIncorporati...","[{'sequence': '1', 'size': '2753500', 'documen...",[],NaN,NaN,NaN,NaN,Item 7. Management&#146;s Discussion and Anal...,Item 7A. Quantitative and Qualitative Disclos...
18,52071c0e897ae34a2ada14aafcb7f993,0001047469-04-035975,320193,AAPL,APPLE COMPUTER INC,APPLE COMPUTER INC (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2004-12-02T18:05:49-05:00,https://www.sec.gov/Archives/edgar/data/320193...,...,https://www.sec.gov/Archives/edgar/data/320193...,"[{'fiscalYearEnd': '0930', 'stateOfIncorporati...","[{'sequence': '1', 'size': '943049', 'document...",[],NaN,NaN,NaN,NaN,Item 7. Management's Discussion and Analysis ...,Item 7A. Quantitative and Qualitative Disclos...
38,f1f5b1e0c54820e8ae4091277ea3ee60,0001193125-04-150689,789019,MSFT,MICROSOFT CORP,MICROSOFT CORP (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2004-09-01T17:03:00-04:00,https://www.sec.gov/Archives/edgar/data/789019...,...,https://www.sec.gov/Archives/edgar/data/789019...,"[{'fiscalYearEnd': '0630', 'stateOfIncorporati...","[{'sequence': '1', 'size': '1086418', 'documen...",[],NaN,NaN,NaN,NaN,ITEM 7. MANAGEMENT&#146;S DISCUSSION AND ANAL...,ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOS...
58,61d0841e460a2f249ee41fdb9eb3fe63,0001193125-05-047032,1018724,AMZN,AMAZON COM INC,AMAZON COM INC (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2005-03-11T06:20:27-05:00,https://www.sec.gov/Archives/edgar/data/101872...,...,https://www.sec.gov/Archives/edgar/data/101872...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '1534914', 'documen...",[],NaN,NaN,NaN,NaN,Item 7. Management&#146;s Discussion and Anal...,Item 7A. Quantitative and Qualitative Disclos...

In [98]:
list(null_1A['filedAt'])

['2007-11-15T16:49:37-05:00',
 '2005-11-30T21:22:48-05:00',
 '2004-12-02T18:05:49-05:00',
 '2004-09-01T17:03:00-04:00',
 '2005-03-11T06:20:27-05:00',
 '2004-02-25T17:25:47-05:00',
 '2005-03-22T14:33:30-05:00',
 '2004-03-29T12:31:52-05:00',
 '2005-09-02T14:17:03-04:00',
 '2005-02-28T14:42:15-05:00',
 '2004-09-10T15:48:09-04:00',
 '2004-02-27T16:10:12-05:00',
 '2005-03-08T08:01:18-05:00',
 '2004-03-15T13:43:57-05:00',
 '2005-03-01T17:14:38-05:00',
 '2004-03-15T17:10:43-05:00',
 '2007-02-21T17:22:31-05:00',
 '2006-03-14T16:15:17-05:00',
 '2005-03-15T16:26:48-05:00',
 '2004-03-11T08:55:39-05:00',
 '2016-02-23T16:17:46-05:00',
 '2015-02-24T16:04:18-05:00',
 '2005-03-02T16:42:32-05:00',
 '2004-02-18T16:17:06-05:00',
 '2005-02-28T11:31:22-05:00',
 '2004-03-15T12:53:35-05:00',
 '2005-03-31T15:34:03-05:00',
 '2004-04-09T16:05:14-04:00',
 '2023-02-14T16:48:22-05:00',
 '2022-02-11T09:52:16-05:00',
 '2021-02-12T10:44:10-05:00',
 '2020-02-14T09:29:40-05:00',
 '2005-03-02T08:12:03-05:00',
 '2004-03-04T13:04:36-05:00',
 '2005-08-29T15:27:31-04:00',
 '2004-09-09T14:52:23-04:00',
 '2008-04-03T16:36:42-04:00',
 '2005-04-11T15:11:28-04:00',
 '2004-04-12T16:22:26-04:00',
 '2005-07-01T06:14:38-04:00',
 '2004-06-25T15:41:34-04:00',
 '2005-03-03T08:36:36-05:00',
 '2004-03-09T12:55:13-05:00',
 '2005-03-11T16:21:00-05:00',
 '2005-03-09T06:03:06-05:00',
 '2004-03-10T16:11:46-05:00',
 '2004-02-26T12:16:19-05:00',
 '2007-02-21T15:53:37-05:00',
 '2006-02-28T13:33:03-05:00',
 '2005-03-04T13:05:52-05:00',
 '2004-02-27T09:38:11-05:00',
 '2005-02-28T06:56:22-05:00',
 '2004-03-03T21:48:04-05:00',
 '2005-11-10T17:04:17-05:00',
 '2004-11-12T17:15:28-05:00',
 '2005-03-01T16:46:19-05:00',
 '2004-03-01T16:38:59-05:00',
 '2006-02-08T16:29:05-05:00',
 '2005-02-02T13:35:09-05:00',
 '2004-02-05T16:55:58-05:00',
 '2005-03-16T14:41:02-05:00',
 '2004-03-02T17:06:33-05:00',
 '2005-03-04T15:02:30-05:00',
 '2004-03-05T12:08:20-05:00',
 '2005-03-25T17:26:13-05:00',
 '2005-02-28T14:29:40-05:00',
 '2004-03-10T11:17:20-05:00',
 '2005-10-31T17:11:23-05:00',
 '2004-11-05T16:21:17-05:00',
 '2005-03-15T16:49:49-05:00',
 '2004-02-27T17:06:16-05:00',
 '2005-02-23T09:28:10-05:00',
 '2004-03-12T17:06:15-05:00',
 '2005-03-07T16:40:19-05:00',
 '2004-03-09T18:34:23-05:00',
 '2005-04-01T11:18:21-05:00',
 '2004-03-18T15:01:42-05:00',
 '2006-02-22T10:36:20-05:00',
 '2005-03-02T12:47:10-05:00',
 '2004-02-24T18:50:37-05:00',
 '2005-03-01T16:42:59-05:00',
 '2004-03-09T15:11:42-05:00',
 '2004-12-13T16:27:49-05:00',
 '2005-07-29T17:12:55-04:00',
 '2004-07-30T17:04:26-04:00',
 '2006-03-09T17:03:03-05:00',
 '2005-03-10T17:04:31-05:00',
 '2004-03-12T15:31:17-05:00',
 '2005-03-14T17:22:16-05:00',
 '2005-02-28T16:11:59-05:00',
 '2004-02-27T16:28:29-05:00',
 '2005-02-24T16:42:01-05:00',
 '2004-03-10T14:17:24-05:00',
 '2019-02-26T16:12:52-05:00',
 '2018-02-27T16:09:47-05:00',
 '2005-02-10T20:23:30-05:00',
 '2004-02-25T09:40:46-05:00',
 '2005-02-18T17:51:02-05:00',
 '2004-02-20T17:50:23-05:00',
 '2005-02-28T16:07:20-05:00',
 '2004-03-04T18:05:16-05:00',
 '2005-03-09T17:21:43-05:00',
 '2004-03-11T17:16:48-05:00',
 '2005-02-25T15:09:37-05:00',
 '2004-03-01T21:56:31-05:00',
 '2005-09-26T17:21:19-04:00',
 '2004-09-24T12:44:51-04:00',
 '2005-03-14T12:13:00-05:00',
 '2004-03-12T14:13:48-05:00',
 '2005-02-25T18:08:33-05:00',
 '2004-02-27T17:25:07-05:00',
 '2019-02-26T16:27:59-05:00',
 '2018-02-27T17:13:57-05:00',
 '2017-02-28T16:23:36-05:00',
 '2016-02-23T16:19:19-05:00',
 '2015-02-24T14:08:09-05:00',
 '2014-02-25T14:13:24-05:00',
 '2013-02-26T15:35:35-05:00',
 '2012-02-28T14:52:20-05:00',
 '2011-02-22T13:08:33-05:00',
 '2010-02-23T13:31:57-05:00',
 '2009-02-24T14:26:00-05:00',
 '2008-02-26T14:06:45-05:00',
 '2007-02-27T15:08:14-05:00',
 '2006-02-28T16:50:07-05:00',
 '2005-02-24T15:39:30-05:00',
 '2004-03-08T15:28:07-05:00',
 '2005-04-13T16:37:25-04:00',
 '2004-04-07T18:25:33-04:00',
 '2005-11-02T17:17:00-05:00',
 '2004-11-03T17:24:17-05:00',
 '2005-03-03T17:41:09-05:00',
 '2004-03-15T06:53:11-05:00',
 '2005-12-20T14:57:28-05:00',
 '2004-12-21T14:05:01-05:00',
 '2005-02-10T17:21:16-05:00',
 '2004-02-05T17:08:15-05:00',
 '2005-02-25T17:04:43-05:00',
 '2004-03-04T12:37:53-05:00',
 '2005-02-25T10:30:28-05:00',
 '2004-02-27T10:58:29-05:00',
 '2017-02-24T17:21:03-05:00',
 '2016-02-26T16:06:12-05:00',
 '2015-02-27T16:25:56-05:00',
 '2005-03-01T10:37:34-05:00',
 '2004-03-01T17:20:34-05:00',
 '2005-12-14T16:57:56-05:00',
 '2004-12-15T16:28:55-05:00',
 '2004-01-13T16:46:22-05:00',
 '2005-03-10T17:27:43-05:00',
 '2004-03-12T15:08:18-05:00',
 '2005-03-15T16:45:54-05:00',
 '2004-03-15T15:13:15-05:00',
 '2005-03-02T16:02:10-05:00',
 '2004-03-11T12:02:36-05:00',
 '2004-12-10T15:37:36-05:00',
 '2005-02-28T17:24:00-05:00',
 '2004-03-05T19:57:34-05:00',
 '2005-02-07T21:16:42-05:00',
 '2004-02-24T09:05:23-05:00',
 '2005-03-10T10:04:27-05:00',
 '2004-03-11T09:28:52-05:00',
 '2005-03-11T17:29:50-05:00',
 '2004-03-11T16:19:56-05:00',
 '2005-06-29T16:30:51-04:00',
 '2004-06-30T14:17:28-04:00',
 '2005-03-14T15:46:56-05:00',
 '2004-02-27T11:30:22-05:00',
 '2005-03-02T16:50:35-05:00',
 '2004-03-12T10:44:45-05:00',
 '2005-03-16T14:48:06-05:00',
 '2004-03-12T16:00:01-05:00',
 '2005-03-10T17:01:56-05:00',
 '2004-03-12T12:13:47-05:00',
 '2005-08-31T16:33:05-04:00',
 '2004-08-30T16:40:05-04:00',
 '2005-03-11T14:52:31-05:00',
 '2005-03-09T17:56:30-05:00',
 '2004-03-15T12:24:21-05:00',
 '2004-03-11T15:48:23-05:00',
 '2007-03-01T15:39:31-05:00',
 '2006-03-10T16:34:38-05:00',
 '2005-03-11T16:19:42-05:00',
 '2004-03-12T12:47:41-05:00',
 '2005-03-14T16:16:57-05:00',
 '2004-03-11T15:54:09-05:00',
 '2005-03-30T17:07:26-05:00',
 '2004-03-31T16:51:35-05:00',
 '2005-03-16T17:07:02-05:00',
 '2004-03-12T16:33:40-05:00',
 '2005-03-08T21:29:09-05:00',
 '2004-03-15T15:17:11-05:00',
 '2005-11-21T17:31:32-05:00',
 '2004-11-30T16:01:23-05:00',
 '2005-08-17T21:59:10-04:00',
 '2004-09-10T12:40:30-04:00',
 '2006-03-16T16:51:23-05:00',
 '2005-03-16T14:42:31-05:00',
 '2004-03-15T16:14:56-05:00',
 '2005-03-30T13:13:43-05:00',
 '2004-03-12T14:29:33-05:00',
 '2012-02-21T07:31:08-05:00',
 '2005-03-11T13:30:59-05:00',
 '2004-03-12T16:01:27-05:00',
 '2005-03-11T16:05:28-05:00',
 '2004-03-12T16:41:33-05:00',
 '2005-03-04T13:28:27-05:00',
 '2004-02-27T17:08:30-05:00',
 '2023-02-24T21:45:33-05:00',
 '2022-02-25T18:35:29-05:00',
 '2021-02-26T16:44:10-05:00',
 '2020-02-21T17:05:55-05:00',
 '2019-02-22T16:50:54-05:00',
 '2018-02-23T08:44:36-05:00',
 '2017-02-24T16:46:05-05:00',
 '2016-02-26T16:45:11-05:00',
 '2015-02-25T17:06:00-05:00',
 '2014-03-03T07:57:17-05:00',
 '2013-03-01T07:49:35-05:00',
 '2012-02-24T09:31:44-05:00',
 '2011-02-25T17:07:08-05:00',
 '2010-02-26T17:00:16-05:00',
 '2006-02-23T19:02:44-05:00',
 '2005-02-28T17:10:27-05:00',
 '2004-03-01T15:06:25-05:00',
 '2005-03-16T13:02:52-05:00',
 '2005-03-15T16:28:43-05:00',
 '2004-03-12T19:58:57-05:00',
 '2004-03-11T16:45:02-05:00',
 '2005-03-03T21:18:24-05:00',
 '2004-03-03T17:05:04-05:00',
 '2005-12-09T16:45:26-05:00',
 '2004-12-13T17:23:05-05:00',
 '2005-03-15T16:55:21-05:00',
 '2004-03-12T17:07:29-05:00',
 '2005-02-25T16:54:53-05:00',
 '2004-02-27T13:37:02-05:00',
 '2008-02-28T16:16:03-05:00',
 '2005-02-25T14:02:17-05:00',
 '2004-03-11T12:30:45-05:00',
 '2005-02-28T21:51:12-05:00',
 '2004-03-01T11:42:39-05:00',
 '2005-03-01T14:53:10-05:00',
 '2004-03-04T17:05:52-05:00',
 '2005-03-04T14:44:12-05:00',
 '2004-03-09T14:50:42-05:00',
 '2005-03-10T17:24:54-05:00',
 '2004-03-11T13:35:36-05:00',
 '2005-03-16T15:34:03-05:00',
 '2004-03-15T15:39:08-05:00',
 '2005-03-11T15:06:27-05:00',
 '2004-03-12T14:16:46-05:00',
 '2005-03-10T15:59:50-05:00',
 '2004-03-05T16:29:45-05:00',
 '2005-03-16T16:02:13-05:00',
 '2004-03-15T16:34:19-05:00',
 '2008-05-30T17:10:38-04:00',
 '2005-06-09T15:38:36-04:00',
 '2004-06-10T16:43:37-04:00',
 '2005-03-23T17:23:27-05:00',
 '2005-11-04T16:21:55-05:00',
 '2004-10-15T15:19:05-04:00',
 '2005-03-10T10:44:06-05:00',
 '2004-03-11T12:24:18-05:00',
 '2005-09-02T12:48:09-04:00',
 '2004-08-30T17:27:34-04:00',
 '2005-07-14T17:00:17-04:00',
 '2004-07-16T12:51:04-04:00',
 '2006-01-12T15:29:57-05:00',
 '2005-01-11T19:47:08-05:00',
 '2004-01-29T16:19:42-05:00',
 '2004-03-10T17:30:30-05:00',
 '2005-02-17T16:35:32-05:00',
 '2004-02-20T10:23:26-05:00',
 '2013-02-22T16:06:50-05:00',
 '2012-02-24T16:47:56-05:00',
 '2011-02-25T17:20:56-05:00',
 '2010-02-26T16:16:58-05:00',
 '2009-03-02T16:27:42-05:00',
 '2008-02-28T16:42:26-05:00',
 '2007-03-01T17:18:36-05:00',
 '2006-03-09T16:53:35-05:00',
 '2005-03-15T18:52:18-05:00',
 '2004-03-11T16:58:14-05:00',
 '2012-02-08T08:33:07-05:00',
 '2011-02-09T08:16:23-05:00',
 '2009-02-11T16:53:24-05:00',
 '2005-03-02T21:06:46-05:00',
 '2004-03-15T16:55:06-05:00',
 '2005-03-16T16:37:48-05:00',
 '2004-03-12T12:56:11-05:00',
 '2005-11-22T16:06:05-05:00',
 '2004-12-13T09:50:05-05:00',
 '2005-02-25T14:33:44-05:00',
 '2004-03-12T15:27:47-05:00',
 '2005-02-22T21:19:03-05:00',
 '2004-02-23T16:39:42-05:00',
 '2004-03-10T16:05:16-05:00',
 '2005-03-01T18:59:46-05:00',
 '2004-03-05T14:59:16-05:00',
 '2005-03-08T17:12:58-05:00',
 '2004-03-12T17:11:39-05:00',
 '2005-03-04T10:30:26-05:00',
 '2004-03-05T09:40:51-05:00',
 '2005-03-16T16:48:25-05:00',
 '2004-04-02T17:12:11-05:00',
 '2004-09-03T15:27:35-04:00',
 '2005-03-16T15:13:04-05:00',
 '2004-03-30T16:58:40-05:00',
 '2008-03-13T16:24:10-04:00',
 '2007-03-15T15:08:50-04:00',
 '2005-04-11T17:15:04-04:00',
 '2005-03-28T16:53:48-05:00',
 '2004-04-05T16:06:32-04:00',
 '2004-03-22T12:00:49-05:00',
 '2005-03-16T14:53:14-05:00',
 '2004-03-10T12:08:30-05:00',
 '2007-02-26T17:27:14-05:00',
 '2006-03-07T17:24:00-05:00',
 '2005-02-28T16:11:46-05:00',
 '2004-02-27T16:41:51-05:00',
 '2005-03-11T15:05:49-05:00',
 '2004-03-12T14:52:18-05:00',
 '2005-09-28T16:25:34-04:00',
 '2004-09-17T12:12:28-04:00',
 '2005-05-12T20:34:43-04:00',
 '2004-06-10T17:29:01-04:00',
 '2005-03-15T16:03:39-05:00',
 '2004-03-10T12:26:19-05:00',
 '2005-02-24T09:00:19-05:00',
 '2004-03-02T17:25:12-05:00',
 '2005-03-15T16:19:46-05:00',
 '2004-03-12T18:45:40-05:00',
 '2005-03-01T14:17:28-05:00',
 '2004-03-01T15:41:49-05:00',
 '2007-02-20T17:16:10-05:00',
 '2005-02-22T09:48:58-05:00',
 '2004-02-03T10:03:17-05:00',
 '2005-11-22T11:23:20-05:00',
 '2004-11-18T16:42:56-05:00',
 '2005-03-17T17:28:08-05:00',
 '2004-03-18T16:57:24-05:00',
 '2005-09-02T13:03:36-04:00',
 '2004-09-03T10:19:42-04:00',
 '2005-03-03T17:08:44-05:00',
 '2004-03-05T14:19:36-05:00',
 '2005-03-15T16:01:55-05:00',
 '2004-02-09T17:24:00-05:00',
 '2005-03-15T18:52:16-05:00',
 '2004-03-15T15:24:37-05:00',
 '2005-03-16T11:13:58-05:00',
 '2004-03-12T14:38:03-05:00',
 '2008-03-28T17:25:54-04:00',
 '2005-04-14T16:36:26-04:00',
 '2004-04-13T16:26:58-04:00',
 '2005-03-07T06:59:15-05:00',
 '2004-02-17T18:08:18-05:00',
 '2005-03-18T16:12:10-05:00',
 '2004-03-24T17:27:56-05:00',
 '2005-08-15T11:41:36-04:00',
 '2004-08-16T10:55:56-04:00',
 '2005-03-02T14:29:02-05:00',
 '2004-02-13T13:47:55-05:00',
 '2005-05-16T17:17:17-04:00',
 '2004-05-14T17:30:27-04:00',
 '2005-03-10T16:23:23-05:00',
 '2004-03-12T17:27:39-05:00',
 '2014-02-27T15:12:04-05:00',
 '2013-02-28T14:42:22-05:00',
 '2012-02-24T09:40:24-05:00',
 '2011-02-25T10:32:13-05:00',
 '2010-02-26T15:55:06-05:00',
 '2009-02-27T13:06:11-05:00',
 '2008-02-29T10:30:03-05:00',
 '2006-03-01T17:14:06-05:00',
 '2005-03-11T19:04:47-05:00',
 '2004-03-12T17:18:51-05:00',
 '2005-03-07T08:34:19-05:00',
 '2004-03-05T17:24:50-05:00',
 '2007-02-28T21:49:32-05:00',
 '2006-03-09T17:19:26-05:00',
 '2005-03-07T16:28:52-05:00',
 '2004-03-12T16:59:11-05:00',
 '2005-03-14T17:04:15-05:00',
 '2004-03-12T14:21:51-05:00',
 '2005-01-27T19:56:08-05:00',
 '2004-02-09T10:55:55-05:00',
 '2005-03-04T17:22:26-05:00',
 '2004-03-12T17:29:30-05:00',
 '2005-09-08T17:56:11-04:00',
 '2004-09-08T10:33:59-04:00',
 '2005-02-25T16:36:18-05:00',
 '2004-03-11T17:51:28-05:00',
 '2005-12-20T16:09:41-05:00',
 '2005-04-15T15:49:13-04:00',
 '2004-03-30T15:29:12-05:00',
 '2005-02-24T18:24:27-05:00',
 '2004-03-03T11:27:56-05:00',
 '2005-03-10T15:21:29-05:00',
 '2004-03-11T15:10:03-05:00',
 '2005-03-07T14:56:57-05:00',
 '2004-03-12T11:44:04-05:00',
 '2005-03-29T16:54:50-05:00',
 '2004-03-10T10:30:42-05:00',
 '2005-05-23T17:04:03-04:00',
 '2004-06-03T17:08:10-04:00',
 '2008-02-26T16:46:01-05:00',
 '2007-02-22T18:07:18-05:00',
 '2006-02-22T18:50:29-05:00',
 '2005-02-23T15:54:49-05:00',
 '2004-02-24T19:07:50-05:00',
 '2005-07-22T13:29:19-04:00',
 '2004-07-19T20:03:53-04:00',
 '2005-03-04T11:53:42-05:00',
 '2004-03-12T14:52:34-05:00',
 '2005-10-26T15:15:13-04:00',
 '2004-10-27T17:25:04-04:00',
 '2006-03-08T17:23:42-05:00',
 '2005-03-16T16:58:23-05:00',
 '2004-03-15T17:17:07-05:00',
 '2005-03-31T17:15:18-05:00',
 '2004-04-08T17:09:54-04:00',
 '2005-03-16T15:54:26-05:00',
 '2004-03-10T16:02:15-05:00',
 '2005-04-01T06:27:46-05:00',
 '2016-02-19T17:15:13-05:00',
 '2015-02-20T17:07:30-05:00',
 '2014-02-20T16:11:04-05:00',
 '2013-02-21T16:08:46-05:00',
 '2005-05-31T06:19:14-04:00',
 '2004-03-15T11:31:23-05:00',
 '2005-02-24T17:07:23-05:00',
 '2004-02-26T11:37:02-05:00',
 '2008-11-20T16:23:47-05:00',
 '2007-12-14T14:07:57-05:00',
 '2005-03-11T17:22:25-05:00',
 '2004-03-15T15:11:13-05:00',
 '2005-07-28T17:15:56-04:00',
 '2004-07-29T17:05:02-04:00',
 '2005-03-16T16:35:24-05:00',
 '2004-03-12T17:20:14-05:00',
 '2005-03-31T13:57:52-05:00',
 '2004-03-10T14:31:56-05:00',
 '2005-11-14T16:53:15-05:00',
 '2004-11-15T16:12:13-05:00',
 '2007-03-01T15:46:17-05:00',
 '2005-03-15T16:28:36-05:00',
 '2004-03-03T16:47:13-05:00',
 '2005-03-01T19:16:45-05:00',
 '2004-03-11T15:47:52-05:00',
 '2005-02-28T16:40:56-05:00',
 '2004-02-27T18:50:33-05:00',
 '2005-03-08T17:32:02-05:00',
 '2004-03-12T17:28:28-05:00',
 '2004-12-10T14:27:35-05:00',
 '2011-09-27T21:14:34-04:00',
 '2008-09-29T17:06:24-04:00',
 '2005-10-14T16:33:50-04:00',
 '2004-10-14T14:37:40-04:00',
 '2011-02-25T16:11:32-05:00',
 '2010-02-26T16:28:00-05:00',
 '2009-02-27T17:21:11-05:00',
 '2008-02-28T16:48:33-05:00',
 '2007-02-27T17:05:48-05:00',
 '2006-03-10T16:24:23-05:00',
 '2005-03-07T17:13:22-05:00',
 '2004-03-08T14:10:40-05:00',
 '2005-03-10T13:42:33-05:00',
 '2004-03-11T17:26:21-05:00',
 '2005-02-18T13:19:15-05:00',
 '2004-02-19T15:22:44-05:00',
 '2008-11-19T17:15:57-05:00',
 '2007-11-27T17:24:46-05:00',
 '2006-12-11T16:47:15-05:00',
 '2005-12-09T13:06:34-05:00',
 '2004-12-14T06:02:55-05:00',
 '2004-11-30T11:40:19-05:00',
 '2005-03-08T17:18:24-05:00',
 '2004-04-12T16:10:48-04:00',
 '2004-03-30T17:28:51-05:00',
 '2005-03-10T13:49:53-05:00',
 '2004-03-25T16:23:19-05:00',
 '2005-02-23T16:24:27-05:00',
 '2004-02-20T15:28:14-05:00',
 '2005-03-04T13:35:32-05:00',
 '2004-02-19T11:51:22-05:00',
 '2008-02-19T17:21:24-05:00',
 '2007-02-20T17:06:15-05:00',
 '2006-02-17T16:34:10-05:00',
 '2005-02-18T12:13:33-05:00',
 '2004-02-20T14:17:54-05:00',
 '2005-03-31T17:25:18-05:00',
 '2004-03-10T14:23:45-05:00',
 '2012-02-22T20:57:23-05:00',
 '2005-03-04T17:27:58-05:00',
 '2004-03-05T16:16:52-05:00',
 '2005-04-14T14:40:28-04:00',
 '2004-04-15T14:50:56-04:00',
 '2008-02-21T17:26:26-05:00',
 '2005-03-16T15:59:25-05:00',
 '2004-03-03T11:34:49-05:00',
 '2005-12-09T16:46:53-05:00',
 '2004-12-10T15:46:43-05:00',
 '2008-12-19T17:27:11-05:00',
 '2007-12-21T17:22:11-05:00',
 '2006-12-22T17:01:47-05:00',
 '2006-01-17T16:47:54-05:00',
 '2005-10-28T16:10:45-04:00',
 '2005-03-31T12:34:29-05:00',
 '2005-03-29T12:22:04-05:00',
 '2005-03-14T19:59:28-05:00',
 '2004-12-21T06:14:39-05:00',
 '2004-10-29T16:17:48-04:00',
 '2004-03-24T16:52:34-05:00',
 '2004-03-15T10:39:46-05:00',
 '2004-03-12T17:56:20-05:00',
 '2005-02-28T16:37:41-05:00',
 '2004-03-05T16:33:55-05:00',
 '2016-03-22T08:40:41-04:00',
 '2015-03-20T16:31:21-04:00',
 '2014-03-20T16:29:57-04:00',
 '2013-03-25T08:18:17-04:00',
 '2010-03-31T09:05:34-04:00',
 '2005-04-12T12:34:27-04:00',
 '2004-03-16T14:37:41-05:00',
 '2005-03-08T14:33:04-05:00',
 '2004-03-12T17:01:56-05:00',
 '2005-09-15T15:55:26-04:00',
 '2004-09-16T10:09:30-04:00',
 '2005-03-15T16:13:26-05:00',
 '2004-03-15T21:14:57-05:00',
 '2023-02-07T13:18:02-05:00',
 '2022-02-04T13:14:35-05:00',
 '2021-02-05T17:09:04-05:00',
 '2020-02-11T16:57:53-05:00',
 '2019-02-13T15:07:24-05:00',
 '2018-02-09T09:50:46-05:00',
 '2017-02-07T12:18:53-05:00',
 '2016-02-05T11:02:03-05:00',
 '2015-02-24T10:16:16-05:00',
 '2014-02-07T11:18:05-05:00',
 '2013-02-11T09:34:14-05:00',
 '2012-02-16T14:27:13-05:00',
 '2011-02-17T10:33:34-05:00',
 '2010-02-17T13:01:33-05:00',
 '2009-02-18T14:57:41-05:00',
 '2008-02-22T12:46:39-05:00',
 '2007-02-27T21:00:59-05:00',
 '2006-03-10T17:32:35-05:00',
 '2005-03-01T12:38:11-05:00',
 '2004-03-08T13:26:00-05:00',
 '2005-02-24T16:18:21-05:00',
 '2004-02-25T16:01:26-05:00',
 '2005-03-16T15:07:48-05:00',
 '2004-03-12T17:00:09-05:00',
 '2005-02-28T15:08:02-05:00',
 '2004-03-12T17:17:53-05:00',
 '2005-02-28T16:22:08-05:00',
 '2004-03-10T16:27:20-05:00',
 '2005-03-15T17:12:15-05:00',
 '2004-03-15T12:52:00-05:00',
 '2005-03-01T11:31:44-05:00',
 '2004-03-09T18:32:46-05:00',
 '2005-09-02T16:55:16-04:00',
 '2004-09-01T12:16:43-04:00',
 '2005-04-15T09:19:34-04:00',
 '2004-04-14T16:46:11-04:00',
 '2005-03-31T16:57:46-05:00',
 '2005-02-11T21:32:09-05:00',
 '2004-03-01T16:43:17-05:00',
 '2005-11-10T16:39:36-05:00',
 '2004-11-19T15:56:40-05:00',
 '2005-03-11T17:14:26-05:00',
 '2004-02-17T12:49:35-05:00',
 '2005-09-02T14:17:03-04:00',
 '2005-02-28T14:42:15-05:00',
 '2004-09-10T15:48:09-04:00',
 '2004-02-27T16:10:12-05:00',
 '2008-02-26T16:02:46-05:00',
 '2005-03-16T13:39:03-05:00',
 '2004-02-26T13:08:05-05:00',
 '2005-08-15T17:02:11-04:00',
 '2004-08-10T16:48:41-04:00',
 '2005-06-07T15:51:28-04:00',
 '2004-06-04T17:21:03-04:00',
 '2006-03-31T14:56:51-05:00',
 '2006-03-31T14:56:51-05:00',
 '2004-03-15T14:21:33-05:00',
 '2004-03-15T14:21:33-05:00',
 '2005-02-17T13:34:43-05:00',
 '2004-02-20T09:19:38-05:00',
 '2005-04-14T16:40:49-04:00',
 '2004-04-13T17:25:47-04:00',
 '2005-03-11T16:48:33-05:00',
 '2004-03-12T15:43:34-05:00',
 '2005-03-03T20:30:36-05:00',
 '2004-03-15T17:27:04-05:00',
 '2005-03-08T17:48:28-05:00',
 '2004-03-05T17:23:44-05:00',
 '2005-03-01T15:01:05-05:00',
 '2004-02-25T15:13:11-05:00',
 '2006-12-22T16:55:42-05:00',
 '2005-12-20T18:43:27-05:00',
 '2005-01-14T16:49:57-05:00',
 '2004-01-16T19:34:55-05:00',
 '2005-03-09T08:03:15-05:00',
 '2004-03-11T14:21:27-05:00',
 '2005-02-25T17:12:18-05:00',
 '2004-02-24T16:59:50-05:00',
 '2005-02-28T21:58:37-05:00',
 '2004-02-25T17:20:09-05:00',
 '2008-02-29T13:13:54-05:00',
 '2005-03-09T17:10:48-05:00',
 '2004-03-12T12:16:04-05:00',
 '2005-03-14T12:18:04-05:00',
 '2004-03-12T18:50:05-05:00',
 '2005-03-08T16:57:35-05:00',
 '2004-03-12T12:53:55-05:00',
 '2007-02-22T17:15:21-05:00',
 '2006-02-23T16:14:00-05:00',
 '2005-02-24T16:56:54-05:00',
 '2004-03-10T18:10:26-05:00',
 '2005-03-08T16:00:15-05:00',
 '2004-03-03T13:10:43-05:00',
 '2005-03-16T16:02:39-05:00',
 '2004-03-15T15:41:45-05:00',
 '2005-03-09T18:37:07-05:00',
 '2004-03-12T17:09:15-05:00',
 '2008-02-29T16:05:46-05:00',
 '2005-03-15T17:29:44-05:00',
 '2004-03-10T13:02:12-05:00',
 '2005-03-15T16:01:24-05:00',
 '2005-02-25T13:20:55-05:00',
 '2004-03-15T12:35:05-05:00',
 '2005-06-15T15:50:38-04:00',
 '2004-06-09T16:55:54-04:00',
 '2009-02-26T18:11:57-05:00',
 '2005-03-04T15:14:37-05:00',
 '2004-03-01T19:39:27-05:00',
 '2005-02-25T13:30:08-05:00',
 '2004-03-15T15:44:57-05:00',
 '2005-03-16T10:55:17-05:00',
 '2004-02-27T16:52:19-05:00',
 '2005-02-22T16:03:05-05:00',
 '2004-03-01T16:02:55-05:00',
 '2021-02-25T16:10:55-05:00',
 '2018-02-22T16:11:02-05:00',
 '2006-03-07T11:52:21-05:00',
 '2005-03-16T12:44:59-05:00',
 '2004-03-15T10:13:03-05:00',
 '2005-03-16T16:39:36-05:00',
 '2004-03-12T16:23:50-05:00',
 '2020-02-28T16:17:53-05:00',
 '2004-03-09T16:24:00-05:00',
 '2005-03-15T16:01:34-05:00',
 '2004-03-05T14:00:33-05:00',
 '2005-03-14T17:14:42-05:00',
 '2005-03-22T14:21:05-05:00',
 '2004-03-15T15:16:49-05:00',
 '2005-03-11T17:58:11-05:00',
 '2004-03-15T17:04:49-05:00',
 '2005-03-15T16:54:58-05:00',
 '2004-03-30T16:25:20-05:00',
 '2005-09-13T15:49:49-04:00',
 '2004-08-30T20:10:15-04:00',
 '2005-03-01T16:28:34-05:00',

In [99]:
[list(null_1A['linkToFilingDetails'])][0][75]

'https://www.sec.gov/Archives/edgar/data/1023052/000118811205000615/t10k-5575.txt'

In [100]:
ex=null_1A.loc[null_1A['filedAt']=="2023-07-14T16:49:34-04:00"]

In [101]:
list(ex['linkToFilingDetails'])

['https://www.sec.gov/Archives/edgar/data/102109/000141057823001476/uuu-20230331x10k.htm']

In [102]:
#make a list of the companies which do not have 1A, 7 and 7A separately
#notethefrequency of each

In [112]:
#how many companies have missing risk factors 1A
((null_1A['companyName']).value_counts())

ODYSSEY RE HOLDINGS CORP     114
PROSPERITY BANCSHARES INC     76
PHELPS DODGE CORP             56
AGILENT TECHNOLOGIES INC      55
CITIGROUP INC                 51
                            ...
FULL HOUSE RESORTS INC         1
American Reprographics CO      1
PHARMATHENE, INC               1
AmpliPhi Biosciences Corp      1
BICYCLE THERAPEUTICS plc       1
Name: companyName, Length: 2851, dtype: int64

In [130]:
#study one of the companies which has 1A risk factors absent
null_1A.loc[null_1A['companyName']=="ODYSSEY RE HOLDINGS CORP"].head(2)

,id,accessionNo,cik,ticker,companyName,companyNameLong,formType,description,filedAt,linkToTxt,...,linkToFilingDetails,entities,documentFormatFiles,dataFiles,seriesAndClassesContractsInformation,periodOfReport,effectivenessDate,10k_risks1A,10k_risks7,10k_risks7A
3053,75b1c8a603ae7225cb6923dbf069dd27,0000909567-05-000513,1137048,ORH-PA,ODYSSEY RE HOLDINGS CORP,ODYSSEY RE HOLDINGS CORP (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2005-03-07T06:59:15-05:00,https://www.sec.gov/Archives/edgar/data/113704...,...,https://www.sec.gov/Archives/edgar/data/113704...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '1782473', 'documen...",[],NaN,NaN,NaN,NaN,Item 7. Management&#146;s Discussion and Anal...,Item 7A. Quantitative and Qualitative Disclos...
3054,d120259c89f1a355c638a404c31c0ee4,0000909567-04-000225,1137048,ORH-PA,ODYSSEY RE HOLDINGS CORP,ODYSSEY RE HOLDINGS CORP (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2004-02-17T18:08:18-05:00,https://www.sec.gov/Archives/edgar/data/113704...,...,https://www.sec.gov/Archives/edgar/data/113704...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '1829652', 'documen...",[],NaN,NaN,NaN,NaN,Item 7. Management&#146;s Discussion and Anal...,Item 7A. \n\n&#160; Quantitative and Qualitat...

In [106]:
#companies having missing 7 (top 5)
((null_7['companyName']).value_counts()).head()

PanAmSat Holding CORP          57
CITIGROUP INC                  51
BANK OF AMERICA CORP /DE/      28
STARRETT L S CO                17
FIRST HORIZON NATIONAL CORP    16
Name: companyName, dtype: int64

In [105]:
#number of companies having missing 7A
((null_7A['companyName']).value_counts()).shape

(1225,)

In [ ]:
#EDA on Risk factor 1A

In [116]:
#create a list of all 1A risks
risk1a=list(df_all['10k_risks1A'])
# print(risk1a[0])

In [125]:
#plot a word count of each risk factor
# Count words in each paragraph
def word_count(risk):
    return len(risk.split(" "))

#count words for a list of paragraphs
def word_count_list(lis):
    counts=[]
    for item in lis:
        c=len(item.split(" "))
        counts.append(c)
    return counts

In [126]:
word_count(risk1a[0])

10226

In [127]:
word_count_list(risk1a[:5])

[10226, 9664, 8791, 7932, 8000]

In [128]:
###group all the 1A risk factors by years in ascending order

In [139]:
df_date=df_all.sort_values(by='filedAt', ascending=True, inplace=False)

In [143]:
df_date.head(1)

,id,accessionNo,cik,ticker,companyName,companyNameLong,formType,description,filedAt,linkToTxt,...,linkToFilingDetails,entities,documentFormatFiles,dataFiles,seriesAndClassesContractsInformation,periodOfReport,effectivenessDate,10k_risks1A,10k_risks7,10k_risks7A
68445,1b27c36e76a04a7af09a4317ebfe6e92,0001096906-04-000005,869495,DWOG,DEEP WELL OIL & GAS INC,DEEP WELL OIL & GAS INC (Filer),10-K,Form 10-K - Annual report [Section 13 and 15(d...,2004-01-05T14:28:13-05:00,https://www.sec.gov/Archives/edgar/data/869495...,...,https://www.sec.gov/Archives/edgar/data/869495...,"[{'fiscalYearEnd': '1231', 'stateOfIncorporati...","[{'sequence': '1', 'size': '65431', 'documentU...",[],NaN,NaN,NaN,NaN,ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...,ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSU...

In [146]:
df_date['10k_risks1A'].tail()

8575      Item 1A. - Risk Factors \n\n&#160; The follow...
12003     ITEM 1A. RISK FACTORS \n\nYou should consider...
22855     ITEM 1A. RISK FACTORS \n\nGlobal Risks \n\nGe...
15047     ITEM 1A. RISK FACTORS \n\nOur business activi...
15849     Item 1A. Risk Factors \n\nSports Business Ris...
Name: 10k_risks1A, dtype: object